default_install_hook_types: [pre-commit, commit-msg]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [--max-line-length=100, --ignore=E501]
        exclude: ^commit_check/__init__.py
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
        exclude: ^testing/resources/
-   repo: local
    hooks:
    -   id: check-message
        name: check message formatting
        description: prevents unconventional commits from being committed.
        entry: commit-check
        args: ["--message"]
        pass_filenames: false
        language: python
        always_run: true
        stages: [commit-msg]
    -   id: check-branch
        name: check branch naming
        description: prevents unconventional branch from being pushed to remote repo.
        entry: commit-check
        args: ["--branch"]
        pass_filenames: false
        language: python
        always_run: true
