name: Commit Check
description: Check commit message formatting, branch naming, referencing Jira tickets, and more
author: shenxianpeng
branding:
  icon: "check-circle"
  color: "green"
inputs:
  message:
    description: check commit message formatting convention
    required: false
    default: 'true'
  branch:
    description: check git branch naming convention
    required: false
    default: 'true'
  author-name:
    description: check committer author name
    required: false
    default: 'true'
  author-email:
    description: check committer author email
    required: false
    default: 'true'
  dry-run:
    description: run checks without failing
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Run commit-check
      id: commit-check
      shell: bash
      run: |
        pip install commit-check
        if [ "${{ inputs.message }}" == "true" ]; then
          commit-check --message
        fi
        if [ "${{ inputs.branch }} " == "true" ]; then
          commit-check --branch
        fi
        if [ "${{ inputs.author-name }} " == "true" ]; then
          commit-check --author-name
        fi
        if [ "${{ inputs.author-email }} " == "true" ]; then
          commit-check --author-email
        fi
        if [ "${{ inputs.dry-run }} " == "true" ]; then
          commit-check --dry-run
        fi
