name: Release

on:
  release:
    branches: [main]
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      # use fetch --all for setuptools_scm to work
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: python -m pip install --upgrade pip twine
    - name: Build wheel
      run: python -m pip wheel -w dist .
    - name: Check distribution
      run: twine check dist/commit_check*
    - name: Publish package to TestPyPI
      if: github.event_name == 'workflow_dispatch' && github.repository == 'commit-check/commit-check'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
      run: twine upload --repository testpypi dist/commit_check*
    - name: Publish package to PyPI
      if: github.event_name != 'workflow_dispatch' && github.repository == 'commit-check/commit-check'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/commit_check*
